### ISSUE TITLE
Where can we get data?

### ISSUE THREAD

**Issue by turbulent0** [MaxHalford/idao-2020-qualifiers#1]
I downloaded files from here https://yadi.sk/d/pdwdp4Lt5X4DMQ, but there were not columns 'x_sim', 'y_sim', 'z_sim', ... in train.

**Comment by MaxHalford** [comment]
Hey there. The data is available [here](https://yadi.sk/d/0zYx00gSraxZ3w). Tell me if you can or can't access the link.

**Comment by turbulent0** [comment]
> Hey there. The data is available [here](https://yadi.sk/d/0zYx00gSraxZ3w). Tell me if you can or can't access the link.

Thanks for quick respond, I downloaded all successfully.
